add logic for checker for field to serdes generator
GetDutchie/brick pull request #214
Opened 2021-09-22 21:20 UTC by mateominato

2021-09-23 17:14 UTC, tshedor requested changes

2021-09-23 17:14 UTC, tshedor commented on packages/brick_build/lib/src/serdes_generator.dart
> +  /// Return a `SharedChecker` for a type via field.
This should be more descriptive. Why is this necessary? Does it relate to other methods? What's the use case? The naming is obvious as to what it does.

2021-09-23 17:14 UTC, tshedor commented on packages/brick_rest_generators/lib/src/rest_deserialize.dart
> +      return '$fieldValue as ${checker.targetType}$defaultValue';
There should be test coverage around this too in the `brick_rest_generators` package

2021-09-23 17:14 UTC, tshedor commented on packages/brick_sqlite_generators/test/sqlite_schema/test_nullable.dart
> +    SchemaColumn('constructor_field_type_mismatch', Column.varchar)
This is good coverage

2021-09-23 17:14 UTC, tshedor commented on packages/brick_sqlite_generators/lib/src/sqlite_deserialize.dart
> +      return '$fieldValue as ${checker.targetType}$defaultValue';
There should also be test coverage around this in the `brick_sqlite_generators` package. It's not guaranteed that only OFWIRB will implement this generator

2021-09-23 17:14 UTC, tshedor commented on packages/brick_offline_first_with_rest_build/test/offline_first_generator/test_nullable_field.dart
> +      nullableRestTrue: data['nullable_rest_true'] as String?,
There's additional testing and implementation in this package around OfflineFirstSerdes.

2021-09-23 19:38 UTC, mateominato commented on packages/brick_offline_first_with_rest_build/test/offline_first_generator/test_nullable_field.dart
> +      nullableRestTrue: data['nullable_rest_true'] as String?,
is this actionable? not sure I understand

2021-09-23 19:47 UTC, tshedor commented on packages/brick_sqlite_generators/lib/src/sqlite_deserialize.dart
> +      return '$fieldValue as ${checker.targetType}$defaultValue';
That's the schema. It doesn't cover the adapter generators

2021-09-23 19:48 UTC, tshedor commented on packages/brick_offline_first_with_rest_build/test/offline_first_generator/test_nullable_field.dart
> +      nullableRestTrue: data['nullable_rest_true'] as String?,
The offline first with rest build introduces a new model type, `OfflineFirstSerdes`. The nullable checks around an OfflineFirstSerdes should be tested too, as they aren't as simple as an `as ?`. They use a constructor that cannot accept a nullable object (i.e. `OfflineFirstSerdes.fromRest(data['my_object'])`)

2021-09-23 22:53 UTC, tshedor reviewed
slight change

2021-09-23 22:53 UTC, tshedor commented on packages/brick_build/lib/src/serdes_generator.dart
> +  /// }
```suggestion
  /// Ex:
  /// ```dart
  ///   class MyClass {
  ///     final String field;
  ///
  ///     MyClass({String? field}): field = field ?? 'default';
  ///   }
  /// ```
```

2021-09-23 22:53 UTC, tshedor commented on packages/brick_rest_generators/test/rest_model_serdes_generator_test.dart
> +      test('constructor_member_field_mismatch', () async {
it's easier to discover test runs by sync'ing the class name and the test name
```suggestion
      test('RestConstructorMemberFieldMismatch', () async {
```

2021-09-23 22:53 UTC, tshedor commented on packages/brick_sqlite_generators/lib/src/sqlite_serdes_generator.dart
> +  /// by the class member.
This is a good sentence.

2021-09-24 19:58 UTC, tshedor requested changes
Small things but now here's the fun part. 

* Add a CHANGELOG to `brick_build` describing the new methods and preference of using `checkerForField`
* Bump `brick_build`'s version in the pubspec; I'll do a release
* Add a CHANGELOG to `brick_rest_genereators`
* Bump `brick_rest_generators` version and the minimum `brick_build` version
* Add a CHANGELOG to `brick_offline_first_with_rest_build`
* Bump the version and the rest and build version

The non-nullable futures will be a breaking change that should be noted in OFWRB

2021-09-24 19:58 UTC, tshedor commented on packages/brick_build/example/file_deserialize.dart
> +          wrappedInFuture ? 'Future<${checker.targetType}>' : '${checker.targetType}';
```suggestion
          wrappedInFuture ? 'Future<${checker.targetType}>' : checker.targetType.toString();
```

2021-09-24 19:58 UTC, tshedor commented on packages/brick_build/test/__helpers__.dart
> +        wrappedInFuture ? 'Future<${checker.targetType}>' : '${checker.targetType}';
```suggestion
        wrappedInFuture ? 'Future<${checker.targetType}>' : checker.targetType.toString();
```

2021-09-24 19:58 UTC, tshedor commented on packages/brick_rest_generators/lib/src/rest_deserialize.dart
> +          wrappedInFuture ? 'Future<${checker.targetType}>' : '${checker.targetType}';
```suggestion
          wrappedInFuture ? 'Future<${checker.targetType}>' : checker.targetType.toString();
```

2021-09-24 23:39 UTC, tshedor approved these changes

2021-09-24 23:42 UTC, merged