offline-queue for Graphql
GetDutchie/brick pull request #227
Opened 2022-01-20 09:26 UTC by Josiassejod1

✅ Create abstract classes for OfflineRequestQueue, SqliteCache, and SqliteCacheManager
✅  Change GraphQL => Graphql globally

2022-01-20 17:05 UTC, tshedor reviewed
Good first pass

2022-01-20 17:05 UTC, tshedor commented on packages/brick_graphql/lib/src/offline_queue/offline_request_queue_graphql.dart
> +class OfflineRequestQueueGraphql {
Naming conventions should be consistent. You created the package with `GraphQL` and I followed that convention through the generator. If it's going to be `Graphql` (which IMO I could defend more than `GraphQL` as both `Rest` and `Sqlite` do not see capitalization despite being acronyms), everything should be appropriately renamed.

2022-01-20 17:05 UTC, tshedor commented on packages/brick_graphql/lib/src/offline_queue/request_sqlite_cache_graphql.dart
> +    return _request;
```suggestion
    return Request(variables: variables, operation: operation);
```

2022-01-20 17:05 UTC, tshedor commented on packages/brick_graphql/lib/src/offline_queue/request_sqlite_cache_graphql.dart
> +    final variables = jsonDecode(data[GRAPHQL_JOB_VARIABLES_COLUMN]);
Why is `GRAPHQL_JOB_OPERATION_TYPE_COLUMN` stored in SQLite if it's not used to recreate the request?

2022-01-20 17:05 UTC, tshedor commented on packages/brick_graphql/lib/src/offline_queue/request_sqlite_cache_manager_graphql.dart
> +class RequestGrapqQLSqliteCacheManager {
I think, more than other files but not excluding them, this could be subclassed instead of a brand new file. All of the methods save `migrate` could be in a super abstract class, and the implementing classes could accept a `tableName` in the constructor.

2022-01-20 20:51 UTC, Josiassejod1 commented on packages/brick_graphql/lib/src/offline_queue/offline_request_queue_graphql.dart
> +class OfflineRequestQueueGraphql {
lets clean it up then

2022-01-20 21:02 UTC, Josiassejod1 commented on packages/brick_graphql/lib/src/offline_queue/request_sqlite_cache_graphql.dart
> +    final variables = jsonDecode(data[GRAPHQL_JOB_VARIABLES_COLUMN]);
thought it was helpful to know what request it was but that can get redundant I guess

2022-01-21 00:16 UTC, tshedor requested changes

2022-01-21 00:16 UTC, tshedor commented on packages/brick_graphql/README.md
> +# Brick Graphql
```suggestion
# Brick GraphQL
```

2022-01-21 00:16 UTC, tshedor commented on .github/workflows/brick_graphql.yaml
> +name: Brick Graphql
```suggestion
name: Brick GraphQL
```

2022-01-21 00:16 UTC, tshedor commented on packages/brick_graphql/README.md
> +Core logic for interfacing with a graphql server with Brick.
```suggestion
Core logic for interfacing with a GraphQL server with Brick.
```

2022-01-21 00:16 UTC, tshedor commented on packages/brick_graphql/pubspec.yaml
> +description: Graphql connector for Brick, a data persistence library. Includes annotations, adapter, model, and provider.
```suggestion
description: GraphQL connector for Brick, a data persistence library. Includes annotations, adapter, model, and provider.
```

2022-01-21 00:16 UTC, tshedor commented on packages/brick_graphql/pubspec.yaml
> +  graphql: ^5.0.0
Why is this necessary versus `gql`?

2022-01-21 00:16 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_queue_graphql_client.dart
> +      if (!isAGraphqlErrorsEmpty(resp)) {
```suggestion
      if (!areGraphqlErrorsEmpty(resp)) {
```

2022-01-21 00:16 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_graphql_sqlite_cache.dart
> +class RequestGraphqlSqliteCache {
This file should be deleted

2022-01-21 00:16 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_graphql_sqlite_cache_manager.dart
> +class RequestGraphqlSqliteCacheManager {
This file should be deleted

2022-01-21 00:16 UTC, tshedor commented on packages/brick_offline_first/pubspec.yaml
> +  graphql: ^5.0.0
Should be handled by the `brick_graphql` import until we have to publish and pub screams at us
```suggestion
```

2022-01-21 06:38 UTC, tshedor requested changes

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_graphql_sqlite_cache_manager.dart
> +            updateAtColumn: GRAPHQL_JOB_UPDATED_AT);
also these should be alphabetized
```suggestion
            updateAtColumn: GRAPHQL_JOB_UPDATED_AT,);
```

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_graphql_sqlite_cache_manager.dart
> +    final jobs = unprocessedRequests.map((data) => sqliteToRequest(data)).cast<Request>();
```suggestion
    final jobs = unprocessedRequests.map(sqliteToRequest).cast<Request>();
```

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  final dynamic request;
If you really want this, it should be `RequestSqliteCache<_Request>` and then this would be `final _Request request`

```suggestion
```

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  ///
```suggestion
```

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  http.Request sqliteToRequest(Map<String, dynamic> data) {
This shouldn't need to be declared here or, if it does, it doesn't need the body it'd be `_Request sqliteToRequest(Map<String, dynamic> data);`

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +    required this.createdAtColumn,
These should be alphabetized

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +          await requestManager.unlockRequest(request, txn);
These changes shouldn't be necessary.....`unlockRequest` can remain a static method on that abstract class.

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +      await requestManager.lockRequest(unlockedRequests.first, txn);
These too shouldn't be necessary

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +  Future<_RequestMethod?> prepareNextRequestToProcess();
There should be some documentation here describing the intent of the method to guide subclass implementations

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache.dart
> +  bool get requestIsPush => ['POST', 'PUT', 'DELETE', 'PATCH'].contains(request.method);
This should be sorted before the default constructor

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache_manager.dart
> +      {DatabaseFactory? databaseFactory, Duration? processingInterval, bool? serialProcessing})
```suggestion
      {DatabaseFactory? databaseFactory, Duration? processingInterval, bool? serialProcessing,})
```

2022-01-21 06:38 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache.dart
> +  RestRequestSqliteCache({request})
```suggestion
class RestRequestSqliteCache extends RequestSqliteCache<http.Request> {
  RestRequestSqliteCache(http.Request request)
```

2022-01-21 22:04 UTC, tshedor requested changes

2022-01-21 22:04 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +          tableName: HTTP_JOBS_TABLE_NAME);
```suggestion
      await RequestSqliteCache.lockRequest(
          data: unlockedRequests.first,
          db: txn,
          lockedColumn: lockedColumn,
          primaryKeyColumn: primaryKeyColumn,
          tableName: tableName,
        );
```

2022-01-21 22:04 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +  // return it if not continue
```suggestion
  /// Find the next job and convert it into a request for a client
  /// to retry.
```

2022-01-21 22:04 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache_manager.dart
> +          updateAtColumn: HTTP_JOBS_UPDATED_AT,
Alpha

2022-01-21 22:04 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  final List<dynamic> requestColumns;
What is this? What is this used for? Why is it `dynamic`?

2022-01-21 22:04 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache_manager.dart
> +  }
Similarly here this can be moved to the abstract

2022-01-21 22:04 UTC, tshedor commented on packages/brick_offline_first/test/offline_queue/__helpers__.dart
> +http.Request restSqliteToRequest(Map<String, dynamic> data) {
This shouldn't be reduplicated from the implementation

2022-01-21 22:57 UTC, Josiassejod1 commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  final List<dynamic> requestColumns;
this is the columns that will be joined on in order to make the SQL command

2022-01-21 22:58 UTC, Josiassejod1 commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  final List<dynamic> requestColumns;
``` 
 whereArgs: requestColumns.map((c) => serialized[c]).toList(),
```

2022-01-22 19:13 UTC, tshedor requested changes

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_rest_request_queue.dart
> +  OfflineRestRequestQueue({required this.client})
All of this can be inherited from the super class
```suggestion
  OfflineRestRequestQueue({required OfflineQueueHttpClient client})
```

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_graphql_request_queue.dart
> +  OfflineGraphqlRequestQueue({required this.client})
```suggestion
  OfflineGraphqlRequestQueue({OfflineQueueGraphqlClient this.client})
```

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_graphql_sqlite_cache.dart
> +  Map<String, dynamic> toSqlite() {
Alpha

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  final String updateAtColumn;
```suggestion
  final String attemptColumn;
  final String createdAtColumn;
  final String lockedColumn;
  final String primaryKeyColumn;
  final _Request request;
  /// Columns used to uniquely identify the request (e.g. body, headers, url, method).
  final List<String> requestColumns;
  final String tableName;
  final String updateAtColumn;
```

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +      }
These still need to be abstracted to a `attemptLogMessage(Map<String, dynamic> responseFromSqlite)`. The super class should not consider its implementations.

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +
```suggestion
```

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +    try {
Why is this wrapped in a `try`? It wasn't wrapped in a `try` before.

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache.dart
> +            updateAtColumn: HTTP_JOBS_UPDATED_AT);
```suggestion
            updateAtColumn: HTTP_JOBS_UPDATED_AT,);
```

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/pubspec.yaml
> +  gql_http_link: ^0.4.0
This is only used in the tests, so it shouldn't be a dependency. And I'd argue that even in the tests it shouldn't be necessary
```suggestion
```

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/test/offline_queue/__helpers__.dart
> +http.Request sqliteToRequest(Map<String, dynamic> data) {
This is implementation that shouldn't be duplicated

2022-01-22 19:13 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_graphql_sqlite_cache.dart
> +class RequestGraphqlSqliteCache extends RequestSqliteCache<Request> {
The naming conventions should be standardized. There's `RestRequestSqliteCache`, `RequestGraphqlSqliteCache`, `RequestGraphqlSqliteCacheManager`, and `RestRequestSqliteCacheManager`. Either the `Request` or the implementation should come first. I'd lean the implementation coming first (`RestRequestSqliteCache`). When you rename the classes please also rename the files.

2022-01-24 19:00 UTC, Josiassejod1 commented on packages/brick_offline_first/lib/src/offline_queue/offline_queue_graphql_client.dart
> +class OfflineQueueGraphqlClient extends Link {
🔗🔗🔗🔗🔗

2022-01-24 19:07 UTC, Josiassejod1 commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +    try {
@tshedor this is compensating for some errors I received with the database closing while running tests

2022-01-24 19:41 UTC, Josiassejod1 commented on packages/brick_offline_first/test/offline_queue/request_sqlite_cache_test.dart
> +        final tempRequest = http.Request('GET', Uri.parse('http://uninserted.com'));
can't access sqliteToRequest without passing a request into the class

2022-01-24 21:24 UTC, tshedor requested changes

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_request_sqlite_cache_manager.dart
> +          primaryKeyColumn: GRAPHQL_JOB_PRIMARY_KEY_COLUMN,
Alpha

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_graphql_request_queue.dart
> +class OfflineGraphqlRequestQueue extends OfflineRequestQueue<OfflineQueueGraphqlClient> {
For consistency with `GraphqlRequest`. The file should be renamed too
```suggestion
class GraphqlOfflineRequestQueue extends OfflineRequestQueue<OfflineQueueGraphqlClient> {
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_graphql_request_queue.dart
> +      Logger('Processing request ${request.operation.operationName}');
```suggestion
      logger.debug('Processing request ${request.operation.operationName}');
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_queue_graphql_client.dart
> +class OfflineQueueGraphqlClient extends Link {
With the file being similarly renamed
```suggestion
class GraphqlOfflineQueueLink extends Link {
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_queue_graphql_client.dart
> +  }
This method isn't necessary
```suggestion
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_queue_graphql_client.dart
> +      final streamAsStream = _inner.request(request).asBroadcastStream();
Does this need to be a broadcast stream? Ideally the stream should only need to be consumed exactly once. 
```suggestion
      final streamAsStream = _inner.request(request);
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +  void process(Timer _timer) async {}
```suggestion
  Future<void> process(Timer _timer);
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_rest_request_queue.dart
> +class OfflineRestRequestQueue extends OfflineRequestQueue<OfflineQueueHttpClient> {
File name too
```suggestion
class RestOfflineRequestQueue extends OfflineRequestQueue<OfflineQueueHttpClient> {
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  void attemptLogMessage(Map<String, dynamic> responseFromSqlite) {}
```suggestion
  /// The output before each attempt
  String attemptLogMessage(Map<String, dynamic> responseFromSqlite);
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +      attemptLogMessage(response);
```suggestion
      logger?.warning('failed, attempt #${response[attemptsColumn]} ${attemptLogMessage(response)}');
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +  // example of usage inside request_sqlite_cache
You want to avoid referencing implementation method documentation unless absolutely necessary. A terse example (`e.g. SqliteProvider`) is acceptable, but largely the abstract is completely independent of the implementation. 
```suggestion
  /// Builds a client-consumable [_RequestMethod] from SQLite row output
```

2022-01-24 21:24 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_request_sqlite_cache.dart
> +        'failed, attempt #${responseFromSqlite[HTTP_JOBS_ATTEMPTS_COLUMN]} in $attemptMessage : $responseFromSqlite');
```suggestion
    return 'in $attemptMessage : $responseFromSqlite';
```

2022-01-25 00:22 UTC, tshedor requested changes
Re: the `logger`s, you can either `Logger get logger;` in the abstract and avoid the don't override fields warning. Or you should pass in a logger name to the super in implementing classes.

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_offline_queue_client.dart
> +class GraphqlOfflineQueueClient extends Link {
imo, not a firm suggestion
```suggestion
class GraphqlOfflineQueueLink extends Link {
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_offline_request_queue.dart
> +  final Logger logger;
```suggestion
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_offline_request_queue.dart
> +            processingInterval: client.requestManager.processingInterval);
```suggestion
      : super(
            client: client,
            databaseName: client.requestManager.databaseName,
            processingInterval: client.requestManager.processingInterval,
          );
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +  final String databaseName;
`client` nor `databaseName` is used in this abstract class. 
```suggestion
abstract class OfflineRequestQueue {
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +    required this.databaseName,
```suggestion
    required String databaseName,
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +
```suggestion
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  /// The output before each attempt
```suggestion
  /// The log output before each attempt
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  String attemptLogMessage(Map<String, dynamic> responseFromSqlite);
This should be alphabetized

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_request_sqlite_cache.dart
> +    return 'failed, attempt #${responseFromSqlite[GRAPHQL_JOB_ATTEMPTS_COLUMN]} in $attemptMessage : $responseFromSqlite';
```suggestion
    return 'in $attemptMessage : $responseFromSqlite';
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart
> +  _RequestMethod? sqliteToRequest(Map<String, dynamic> data);
Alphabetized

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_offline_request_queue.dart
> +
```suggestion
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/rest_offline_request_queue.dart
> +  })  : logger = Logger('RestOfflineRequestQueue'),
```suggestion
  })  : 
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/test/offline_queue/request_sqlite_cache_manager_test.dart
> +        expect(req, isNotNull);
This test shouldn't change
```suggestion
        expect(req, isNull);
```

2022-01-25 00:22 UTC, tshedor commented on packages/brick_offline_first/test/offline_queue/request_sqlite_cache_manager_test.dart
> +        expect(await requestManager.prepareNextRequestToProcess(), isNotNull);
```suggestion
        expect(await requestManager.prepareNextRequestToProcess(), isNull);
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_offline_queue_link.dart
> +      : _logger = Logger('GraphqlOfflineQueueClient#${requestManager.databaseName}');
```suggestion
      : _logger = Logger('GraphqlOfflineQueueLink#${requestManager.databaseName}');
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/graphql_offline_request_queue.dart
> +  GraphqlOfflineRequestQueue({required this.client})
```suggestion
  GraphqlOfflineQueueLink link;

  /// This mutex ensures that concurrent writes to the DB will
  /// not occur as the Timer runs in sub routines or isolates
  bool _processingInBackground = false;

  GraphqlOfflineRequestQueue({required this.link})
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +  void process(Timer _timer) async {}
```suggestion
  void process(Timer _timer);
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +  late Timer? _timer;
```suggestion
  Timer? _timer;
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +  final String databaseName;
```suggestion
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +
```suggestion
```

2022-01-25 05:44 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache.dart
> +  _Request sqliteToRequest(Map<String, dynamic> data);
Alpha sorted _before_ static methods. Same for `toSqlite` and `unlock`.

2022-01-25 05:48 UTC, tshedor commented on packages/brick_offline_first/lib/src/offline_queue/offline_request_queue.dart
> +  Logger get logger => Logger('OfflineRequestQueue#$databaseName');
This is created/assigned on initialization and should not be a computed getter.

2022-01-25 23:24 UTC, tshedor approved these changes

2022-01-25 23:57 UTC, merged