feat(supabase): support realtime subscription #454
GetDutchie/brick pull request #472
Opened 2024-10-28 23:09 UTC by tshedor

This resolves #454 's work with collaboration from @Shreemanarjun 

I need help validating this code. Early testers are greatly appreciated. 

To try this PR out before it's merged, add the following to your `pubspec.yaml`:

```yaml
dependency_overrides:
  brick_offline_first_with_supabase:
    git:
      url: git@github.com:GetDutchie/brick.git
      ref: supabase-subscription
      path: packages/brick_offline_first_with_supabase
  brick_offline_first:
    git:
      url: git@github.com:GetDutchie/brick.git
      ref: supabase-subscription
      path: packages/brick_offline_first
  brick_sqlite:
    git:
      url: git@github.com:GetDutchie/brick.git
      ref: supabase-subscription
      path: packages/brick_sqlite
  brick_supabase:
    git:
      url: git@github.com:GetDutchie/brick.git
      ref: supabase-subscription
      path: packages/brick_supabase
```

2024-10-29 05:58 UTC, jtkeyva commented
anything special i need to do other than add this? 
```
Resolving dependencies...
Git error. Command: `git clone --mirror git@github.com:GetDutchie/brick.git /Users/jt/.pub-cache/_temp/dirrx6cUM`
stdout: 
stderr: Cloning into bare repository '/Users/jt/.pub-cache/_temp/dirrx6cUM'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /Users/jt/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/jt/.ssh/known_hosts:2
Host key for github.com has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
exit code 69
```

2024-10-29 06:03 UTC, jtkeyva commented
sorry...can't get it to build. a zillion errors

2024-10-29 06:11 UTC, tshedor commented
You can resolve the git issue by replacing `git@github.com:` with `https://github.com/`

2024-10-29 13:17 UTC, lohnn commented
The payload for the old record when deleting seems to only include the id of the deleted row.
This is most likely why https://github.com/GetDutchie/brick/issues/454#issuecomment-2438911098 fetches the row from the local sqlite database using the id before deleting it.

Your current implementation expects the `payload.oldRecord` to include all columns, and this does not work (at least not on my machine).

2024-10-29 13:18 UTC, lohnn commented
Inserts and updates seem to work great so far however!

2024-10-29 16:12 UTC, tshedor commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +                memoryCacheProvider.upsert<TModel>(instance, repository: this);
Great suggestion

2024-10-29 16:13 UTC, tshedor commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +  /// `query` is an optional query to filter the data. The query **must be** one level -
Another great catch

2024-10-29 16:34 UTC, lohnn requested changes
Looks promising, and it looks like it should now delete my local rows on remote deletion when following stack with breakpoint.
It does not seem to actually remove the row locally. Maybe the problem is on me?

2024-10-29 16:54 UTC, tshedor commented
@lohnn Are you receiving `results.first`, assuming the breakpoint [is here](https://github.com/GetDutchie/brick/pull/472/files#diff-1d08a9b79d8bc8ec2c00871223c1a82a2f5447374491984afa02fb7e14e19e55R292)? Are any exceptions thrown?

2024-10-29 17:05 UTC, lohnn commented
Hmmm...
After clearing my local sqlite database and retrying again it works! It was on my side :)

Something else I found however, is that running delete from the app (and not from the supabase database), it does not update the UI that the item is deleted. After a hot restart it is in sync.

2024-10-29 17:10 UTC, lohnn commented
Upserting (both insert and update) from local works perfectly fine however!

2024-10-29 17:15 UTC, lohnn commented
> Hmmm... After clearing my local sqlite database and retrying again it works! It was on my side :)
> 
> Something else I found however, is that running delete from the app (and not from the supabase database), it does not update the UI that the item is deleted. After a hot restart it is in sync.

From what I can gather `queriesController` seems to be empty in `notifySubscriptionsWithLocalData` on delete from local.
Also, introspecting the `subscriptions` field's list, it seems to be empty too.

2024-10-29 17:18 UTC, tshedor commented
@lohnn Ok, that's great news. I feel very confident in these unit tests, so glad to hear that it's working now.

Before I address your comment, I want to say many, many thanks for the review. You had great feedback.

> Something else I found however, is that running delete from the app (and not from the supabase database), it does not update the UI that the item is deleted. After a hot restart it is in sync.

Architecturally, this was a trade-off, and I'm glad to have this discussion now. I'd appreciate your feedback on the thought process.

By allowing configuration for Supabase's different events (`.insert`, `.update`, etc), there could be multiple different streams listening to multiple different events. So the map that coordinates the subscriptions is keyed by `[TModel][PostgresChangeEvent][Query]StreamController`. The local subscription (`super.subscribe`) is keyed by `[TModel][Query]StreamController`. 

The trade-off comes in supporting multiple event listeners for the same `TModel`/query **OR** supporting the latest event listener for `TModel`/query. I chose the former, which means that the stream is only triggered on a real time update. My justification was that Supabase will notify the client regardless, so only one stream is necessary (at the expense of breaking the OfflineFirst principle, but this has become a much more gray area).

The alternative to this would having two stream controllers - one that's the Supabase stream controller (`supabaseRealtimeSubscriptions`) that handles the remote cancel, and the other that's the local subscribe (`subscriptions`). The Supabase controller would always be returned, but would handle some management and some cancellation of the local subscriptions. This would get extremely convoluted and wouldn't be intuitive...however, you've raised this point because the implemented behavior is not intuitive. 

What are your thoughts?

2024-10-29 17:20 UTC, tshedor commented
By intuitive, I mean that during stream cleanup, the Supabase controller may remove a local controller.

Actually, I think I have an idea.

2024-10-29 17:32 UTC, lohnn commented
Aha, you are very much right in that the Supabase stream does send a `delete` action back to the app (as well as insert and update). So if I understand this particular problem correctly:
1. We delete locally
2. We delete remote - and don't trigger a refresh
3. Remote sends a delete action back
4. This delete action tries to trigger a delete remove, but this will not update the UI, as we already deleted the row locally?

I have personally not spent enough time and thought process understanding the underlying problem to form an opinion in how to best solve it. But if I understand your latter comment you may have a solution?

2024-10-29 17:33 UTC, lohnn commented
Also, you are very welcome! Happy to help 🫡

2024-10-29 18:02 UTC, tshedor commented
@lohnn Alright, I think this should do it. Now it's properly offline first and will fire a response when something is deleted locally.

If your UI does not refresh, can you please confirm you have adequate equality comparison set up (`Equatable` or `hashCode`, anything to make sure there's deep list comparison to trigger Flutter's state change)?

2024-10-29 20:03 UTC, lohnn commented
As far as I can see all CRUD operations seems to be working both from client and server.
Now I'll just look through the code before you get the big LGTM 👍

2024-10-29 20:08 UTC, lohnn approved these changes
LGTM
Awesome work 🤩

2024-10-29 22:52 UTC, jtkeyva commented
thanks guys this is really a giant step in the right direction. are we getting into CRDT territory?

i think it should work just like users expect it it to... like firebase does. users don't care what happens behind the scenes even if it's held together by duct-tape as long as it works reliably. i am not qualified to give much architectural advice. i do see an opportunity for supabase to support/acquire something like this if it truly is a simple and powerful as firebase offline and sync capabilities.

2024-10-30 17:16 UTC, mateominato approved these changes
i've never used supabase but naively this seems logically

2024-10-30 17:16 UTC, mateominato commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +              Map<Query, StreamController<List<OfflineFirstWithSupabaseModel>>>>>
lol

2024-10-30 17:16 UTC, mateominato commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +              Map<Query, StreamController<List<OfflineFirstWithSupabaseModel>>>>>
at some point it might be a good idea to alias some of these longer types, but outside scope of this PR

2024-10-30 17:16 UTC, mateominato commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +    });
optionally; i think this would be easier to read inverted
```suggestion
      if (columnsToFields[entry.key] != null) {
        acc[columnsToFields[entry.key]] = entry.value;
      }
      return acc;
    });
```

2024-10-30 17:16 UTC, mateominato commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +  @visibleForOverriding
this is cool

2024-10-30 17:16 UTC, mateominato commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +    }
you could also do this with a forEach, but maybe this is cleaner

2024-10-30 17:18 UTC, mateominato approved these changes

2024-10-30 17:20 UTC, merged

2024-10-30 18:09 UTC, lohnn commented on packages/brick_offline_first_with_supabase/lib/src/offline_first_with_supabase_repository.dart
> +    }
I'd argue that for..in is much clearer than forEach almost every time at least :)